import type { Building } from '../types';

export const MOCK_BUILDINGS: Building[] = [
  {
    id: 'ict-entrance',
    name: 'ICT Faculty Entrance',
    shortName: 'ICT-GATE',
    type: 'FACULTY',
    description: 'Main entrance of the Faculty of Information & Communication Technology, KWASU Malete. All ground floor rooms accessible from here.',
    latitude: 8.723479,
    longitude: 4.482587,
    address: 'Faculty of ICT, KWASU, Malete, Kwara State',
    openingHours: 'Mon–Fri: 7:00 AM – 9:00 PM',
    phone: '+234-031-555-0200',
    email: 'ict@kwasu.edu.ng',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of Information & Communication Technology',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [
      { id: 'cs-dept', name: 'Computer Science', code: 'CSC', facultyId: 'fac-ict' },
      { id: 'it-dept', name: 'Information Technology', code: 'IT', facultyId: 'fac-ict' },
      { id: 'cy-dept', name: 'Cyber Security', code: 'CYB', facultyId: 'fac-ict' },
      { id: 'se-dept', name: 'Software Engineering', code: 'SWE', facultyId: 'fac-ict' },
    ],
  },
  {
    id: 'ict-auditorium',
    name: 'ICT Auditorium',
    shortName: 'AUDITORIUM',
    type: 'LECTURE_HALL',
    description: 'Main ICT Faculty Auditorium. Ground floor. Used for large lectures, seminars, conferences and faculty events. Seats 500+ students.',
    latitude: 8.723685,
    longitude: 4.482222,
    openingHours: 'Mon–Sat: 7:00 AM – 9:00 PM',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-lre',
    name: 'Lecture Room E',
    shortName: 'LR-E',
    type: 'LECTURE_HALL',
    description: 'Lecture Room E — Ground floor. ICT Faculty undergraduate lectures and tutorials.',
    latitude: 8.723633,
    longitude: 4.482161,
    openingHours: 'Mon–Sat: 7:00 AM – 9:00 PM',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-lrf',
    name: 'Lecture Room F',
    shortName: 'LR-F',
    type: 'LECTURE_HALL',
    description: 'Lecture Room F — Ground floor. ICT Faculty undergraduate lectures and tutorials.',
    latitude: 8.723537,
    longitude: 4.482112,
    openingHours: 'Mon–Sat: 7:00 AM – 9:00 PM',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-lrg',
    name: 'Lecture Room G',
    shortName: 'LR-G',
    type: 'LECTURE_HALL',
    description: 'Lecture Room G — Ground floor. ICT Faculty undergraduate lectures and tutorials.',
    latitude: 8.723598,
    longitude: 4.482223,
    openingHours: 'Mon–Sat: 7:00 AM – 9:00 PM',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-lrh',
    name: 'Lecture Room H',
    shortName: 'LR-H',
    type: 'LECTURE_HALL',
    description: 'Lecture Room H — Ground floor. ICT Faculty undergraduate lectures and tutorials.',
    latitude: 8.723470,
    longitude: 4.482379,
    openingHours: 'Mon–Sat: 7:00 AM – 9:00 PM',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-printing-lab',
    name: 'Printing Laboratory',
    shortName: 'PRINT-LAB',
    type: 'LAB',
    description: 'ICT Printing Laboratory — Ground floor. Printing services, document production and digital printing facility for students and staff.',
    latitude: 8.723640,
    longitude: 4.482428,
    openingHours: 'Mon–Fri: 8:00 AM – 5:00 PM',
    phone: '+234-031-555-0225',
    floor: 1,
    isEmergency: false,
    isAccessible: true,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
  {
    id: 'ict-nlp-lab',
    name: 'NLP Laboratory',
    shortName: 'NLP-LAB',
    type: 'LAB',
    description: '⚠️ UPSTAIRS — Natural Language Processing Laboratory. First floor. Advanced AI and machine learning research facility. Take staircase from main entrance.',
    latitude: 8.723642,
    longitude: 4.482151,
    openingHours: 'Mon–Fri: 8:00 AM – 6:00 PM',
    phone: '+234-031-555-0220',
    floor: 2,
    isEmergency: false,
    isAccessible: false,
    facultyId: 'fac-ict',
    faculty: {
      id: 'fac-ict',
      name: 'Faculty of ICT',
      code: 'ICT',
      color: '#00E5C0',
    },
    departments: [],
  },
];
